name: push to ec2 using docker

on:
  push:
    branches: [main]

jobs:
  running-test:
    name: Running Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22"
      - name: Run Test
        run: go test -v ./... -cover

  build-image:
    name: Image Build
    runs-on: ubuntu-latest
    needs: running-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Image Build
        run: docker build -t nafidinara/wishlist-api:1.0 .
      - name: DockerHub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}
      - name: Image Push
        run: docker push nafidinara/wishlist-api:1.0

  deploy-to-ec2:
    name: Deploy To AWS EC2
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY_PAIR }}
          script: |
            cd /home/ec2-user/wishlist-api
            docker stop wishlist-api || true && docker rm wishlist-api || true
            docker pull nafidinara/wishlist-api:1.0
            docker run -d --name wishlist-api -p 80:8080 nafidinara/wishlist-api:1.0
            touch .env && echo ${{ secrets.DB_HOST }} > .env && echo ${{ secrets.DB_NAME }} >> .env && echo ${{ secrets.DB_PASSWORD }} >> .env && echo ${{ secrets.DB_USERNAME }} >> .env && echo ${{ secrets.SECRET_TOKEN }} >> .env
            docker cp .env wishlist-api:/
            docker restart wishlist-api